language: node_js

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

branches:
  only:
    - master
    - /^release\/.+$/

after_success:
  - npm install -g @zeus-ci/cli
  - zeus upload -t "application/tar+npm" *.tgz

install: yarn --ignore-engines
node_js: "12"

matrix:
  include:
    - env: NAME="test"
      script: yarn test

    - env: NAME="deploy"
      script: yarn build && yarn pack

notifications:
  webhooks:
    urls:
      - https://zeus.ci/hooks/f41c0b0c-c4de-11e7-b821-0a580a280838/public/provider/travis/webhook
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
