# taken from https://getsentry.github.io/craft/github-actions/#changelog-preview-reusable-workflow
name: Changelog Preview
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled, unlabeled]

jobs:
  changelog-preview:
    uses: getsentry/craft/.github/workflows/changelog-preview.yml@v2
    secrets: inherit
