# taken from https://getsentry.github.io/craft/github-actions/#changelog-preview-reusable-workflow
name: Changelog Preview
on:
  pull_request:
    types: [opened, synchronize, reopened, edited, labeled]

jobs:
  changelog-preview:
    uses: getsentry/craft/.github/workflows/changelog-preview.yml@0ca5e6d874c893fbaa8605e24e2835113f29f119
    secrets: inherit
